### ISSUE TITLE
Simple types with `pattern` field are not always validated

### ISSUE THREAD

**Issue by injeniero** [contiamo/openapi-generator-go#111]
Schemas:
```
components:
  schemas:

    IPv4:
      type: string
      example: 192.168.1.56
      pattern: ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$
      minLength: 7

    WrapIP:
      type: object
      required:
          - in_ip
      properties:
        in_ip:
          $ref: "#/components/schemas/IPv4"
        out_ips:
          type: array
          items:
            $ref: "#/components/schemas/IPv4"
```

# Current Behavior

It will add the pattern to the generated `model_wrap_ip.go` file, instead of `model_i_pv4.go`, this makes the pattern validation to be applied only to the `ip` field, but not the items of `out_ips`

model_i_pv4.go:
```
// IPv4 is a value type.
type IPv4 string
```

model_wrap_ip.go:
```
// wrapIPInIpPattern is the validation pattern for WrapIP.InIp
var wrapIPInIpPattern = regexp.MustCompile(`^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$`)

// WrapIP is an object.
type WrapIP struct {
	// InIp:
	InIp IPv4 `json:"in_ip" mapstructure:"in_ip"`
	// OutIps:
	OutIps []IPv4 `json:"out_ips,omitempty" mapstructure:"out_ips,omitempty"`
}

// Validate implements basic validation for this model
func (m WrapIP) Validate() error {
	return validation.Errors{
		"inIp": validation.Validate(
			m.InIp, validation.Required, validation.Length(7, 0), validation.Match(wrapIPInIpPattern),
		),
		"outIps": validation.Validate(
			m.OutIps,
		),
	}.Filter()
}
```

# Expected Behavior

The regexp and validation should be added in `model_i_pv4.go`, only required field validation should happen in `model_i_pv4.go`.

model_i_pv4.go:
```
// pattern is the validation pattern for IPv4
var pattern = regexp.MustCompile(`^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$`)

// IPv4 is a value type.
type IPv4 string

// Validate implements basic validation for this model
func (v IPv4) Validate() error {
	return validation.Validate(v, validation.Length(7, 0), validation.Match(pattern))
}
```

model_wrap_ip.go:
```
// WrapIP is an object.
type WrapIP struct {
	// InIp:
	InIp IPv4 `json:"in_ip" mapstructure:"in_ip"`
	// OutIps:
	OutIps []IPv4 `json:"out_ips,omitempty" mapstructure:"out_ips,omitempty"`
}

// Validate implements basic validation for this model
func (m WrapIP) Validate() error {
	return validation.Errors{
		"inIp": validation.Validate(
			m.InIp, validation.Required,
		),
		"outIps": validation.Validate(
			m.OutIps,
		),
	}.Filter()
}
```

**Comment by injeniero** [comment]
@LucasRoesler I hope you are doing well! We just run into this problem and thought on checking if you guys can fix it. Let me know if you prefer us to create a PR. 

Thanks!

**Comment by LucasRoesler** [comment]
Hi @injeniero , thanks for the report. I have to look into it and play with it a bit. Your expected code is definitely what I expected as well

**Comment by LucasRoesler** [comment]
@injeniero I see what is happening. In the model generation we have 4 kinds of models and each has a separate template, you can see it in the template folder
```
enum.gotpl
model.gotpl
oneof.gotpl
value.gotpl
```

The last one is important and is used for models that are just alias of built-in data types. Which is exactly what happens here. `IPv4` is just an alias for a `string`.  You also see it used here https://github.com/contiamo/openapi-generator-go/blob/e56ce04f8f17d777f46365d43d51fc77fbc59c7b/pkg/generators/models/models.go#L252

Additionally, we don't fill in the validation metadata for these Value kinds https://github.com/contiamo/openapi-generator-go/blob/e56ce04f8f17d777f46365d43d51fc77fbc59c7b/pkg/generators/models/models.go#L171

Part of the reason for this is that we can not provide a field name for the validation error like we do when a value is used in a struct. Normally, these values are used as struct fields, so the validation is applied at the struct level where we can provide a name for which data is failing. 

This clearly doesn't work well when you also want to use the value in an array, there you need the inherited validation. 

Two solutions immediately come to me

1. try to push validation to the Value level. I don't think it is too hard to add the validation information and to add the required method to the value template. But we need to adjust how validation in a struct behaves because we need to skip the validation metadata if the field is a Value _or_ we keep the validation at the struct level but need to use a `validation.Skip` to tell it to skip the validation at the Value level. 
2. add more logic to the validation generation for fields that are arrays. This one is a lot less clear to me right now.

I am leaning toward (1) because I can see the details a bit more clearly and I think it is probably closer to what people expect. If the Value alias has validation information, the Value alias should be validatable. 

@injeniero does it make sense? do you see an alternative solution?

**Comment by injeniero** [comment]
I still think validation should be done as close as possible to the actual type, so option 1) is what I think should be done. 

I was checking the code for validation.Validate and I think it will just work as expected without you needing to do anything special, as long as you add the Struct field specific validation which I think it is just the required property.

This is the doc for that function:
```
// Validate validates the given value and returns the validation error, if any.
//
// Validate performs validation using the following steps:
// 1. For each rule, call its `Validate()` to validate the value. Return if any error is found.
// 2. If the value being validated implements `Validatable`, call the value's `Validate()`.
//    Return with the validation result.
// 3. If the value being validated is a map/slice/array, and the element type implements `Validatable`,
//    for each element call the element value's `Validate()`. Return with the validation result.
```

**Comment by LucasRoesler** [comment]
I think we both agree on the fix. 

I won't be able to fix it in the next couple of days, perhaps I will have some time on Friday. 

If you (or someone on your team) has time or motivation before the weekend, feel free to send a PR. Otherwise I will try to fix it at the end of the week.

**Comment by injeniero** [comment]
I will check as well if I can fix it.

Sadly, last time I tried to fix something it took me many days to arrive to a barely working solution, and you then fixed it with minimal changes and in no time 😄 

It is clear I need more time in the code to better understand where changes should go. But, I will still give it a try if get a few hours this week.

Thanks!!
